### PR TITLE
BLE FS API Commands Implemented

### PR DESCRIPTION
**Pull request by JenJell**
Here is the first pull request for the BLE FS. In it, I have:

- Created a debug terminal-like interface to test everything.
- Implemented the `read`, `rm`, `ls`, `mkdir`, and `mv` commands.

`write` functionality is not implemented yet, but I will hopefully have it finished soon.

Also, while working on this, I came across the InfiniTime settings file. Upon looking into it, I realized that I should be able to use it to sync settings across the watch and phone, which I think would be a cool feature.
IMG_3939
Note: In the picture above, the console only displays the first three settings. However, the file contains more than just these.

### CODE REVIEW

**Comment by JenJell** [comment]
`write` functionality has been added, marking the completion of the BLE FS API integration. Now next I am going work on uploading [external resource packages](https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/gettingStarted/updating-software.md#updating-resources) to the watch, though I will separate that into a different pull request.

**Review by liamcharger — APPROVED** [review]
Awesome work @JenJell! Thank you!

**Comment by liamcharger** [comment]
Hm, looks like I missed something; when using the read command to read the settings.dat (which is a very good idea to sync settings with the phone and watch), I get a crash on this line:

`for idx in 16...responseData.count - 1`

With the fatal error: 

`Fatal error: Range requires lowerBound <= upperBound`

**Comment by JenJell** [comment]
That is strange. Well, I created a bug fix to prevent the app from crashing. However I am still investigating why the watch was not sending any data to the app. Since I am unable to recreate the issue on my end, I was wondering if you could provide what version of InfiniTime you are running? Also, could you run the bug fix pull request I made and let me know what the error print statement outputs for you?

**Comment by liamcharger** [comment]
I'm running InfiniTime 1.14. I ran the bug fix but the crash still occurs. The print statement isn't executing. I don't know if it's with your code, though. I was just recently shipped a new PineTime because my memory chip had some signs of corruption, so there's a possibility it has something to do with that.

**Comment by liamcharger** [comment]
I just added a print statement to print the count of the responseData, and it printed '16'. So it's getting past the if statement but crashing because in the `for` loop the responseData count is being subtracted by one.

**Comment by JenJell** [comment]
Oh, the if statement is supposed to be `if responseData.count > 16 {}` not `if responseData.count > 15 {}`, so that would be why it is still crashing. By the way, are your PineTime settings persistent after a reboot?

**Comment by liamcharger** [comment]
Right, changing the if statement to 16 fixed the crash. The print statement prints: `ERROR: debug info - chunkOffset: 0, chunkLength: 0, totalLength: 0`. The watch will persist settings, but I can't run the bootloader on it because it will bootloop, so I had to unseal the watch and reflash it with the firmware without the bootloader. This is because the bootloader relies on the memory chip and doesn't have any safeguards to check for corrupted hardware. The watch will occasionally freeze and reboot with the all the external resources erased, though.

**Comment by JenJell** [comment]
Okay, I am not exactly sure why that would cause a problem. After all, InfiniTime seems to still be able to read the settings file. However, I do have an unsealed watch so I will try to recreate the problem using my device.

**Comment by liamcharger** [comment]
Ok, hopefully you'll be able to recreate the issue and find a fix!

**Comment by liamcharger** [comment]
Also, I don't think I mentioned this earlier, not only does the read command not work, but neither do the rest of the FS commands. So chances are it's specifically an issue with my device.

**Comment by liamcharger** [comment]
@JenJell I recently erased my external resources and the app began interacting with the FS correctly! 🥳 Your implementation is sound, it was just an issue with my PineTime!

**Pull request merged**
