### PR TITLE
Retrieving weather information using WeatherAPI 

### PR DESCRIPTION
**Pull request by JenJell**
WeatherAPI has been added and now retrieves the same kind of information as NWS.

### CODE REVIEW

**Review by liamcharger — APPROVED** [review]
This looks good to me! I'll provide an API key for WeatherAPI as soon as this PR is merged. Also, I think the _weather_ branch is ready to merge into _main_, are there any more changes that you're planning?

**Comment by JenJell** [comment]
I believe we're about ready for the branch to be merged. I just want to implement a toggle for the simple weather service and I’d like to finish adding the code that decides the current weather condition icon for the watch.

**Comment by liamcharger** [comment]
Ah, that's right, the icon completely slipped my mind. Also, what do you think about a small weather display, possibly under the steps, heart rate, software update, and battery buttons in the DeviceView? I had been beginning to implement it and made a commit, but then decided against it until I had some feedback.

**Comment by ocdtrekkie** [comment]
Is there any way to use this while avoiding precise location info being transmitted to third parties? I notice lat and long variables, which is concerningly specific.

**Comment by liamcharger** [comment]
Well, for the NWS API, there doesn't appear to be a way to avoid using the latitude and longitude variables, but you can turn off precise location for InfiniLink in Location Services to get a more rough location.

**Comment by JenJell** [comment]
@ocdtrekkie, like @liamcharger said, there's not much that can be done about that for the NWS API. Though, I could add an option for the user to set a city name instead of using the current location. That way we're only sending the lon and lat of a nearby city to the API and your precise location never leaves your device.

**Comment by ocdtrekkie** [comment]
I would definitely prefer to set my home city and have it send that to the API then send my location info, if that's possible with the API in question. I rarely am far enough from my home weather area for current-location-based weather lookup to be exceptionally useful.

**Comment by liamcharger** [comment]
Also, giving the user an option to choose between a precise location and a nearby city might be a good idea.

**Comment by JenJell** [comment]
@liamcharger I think adding a small weather display would be a nice touch. We could also make it a shortcut that leads to a settings page for the weather API.

**Comment by liamcharger** [comment]
@JenJell sounds good! I'll build the UI with dummy data, then you can implement the real data because I was having a few issues when I was implementing it earlier. Does that sound good?

**Comment by JenJell** [comment]
@liamcharger, sounds good to me.

**Comment by liamcharger** [comment]
Ok @JenJell, I implemented a dummy weather display. You're free to implement the real data. Note: I will implement a settings option where the user can select their preferred weather format.

**Pull request merged**
